[package]
name = "cw1155"
description = "Definition and types for the CosmWasm-1155 interface"

version       = { workspace = true }
edition       = { workspace = true }
license       = { workspace = true }
repository    = { workspace = true }
homepage      = { workspace = true }
documentation = { workspace = true }

[dependencies]
cw-utils = { workspace = true }
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
cosmwasm-schema = { workspace = true }
cw-storage-plus = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
